version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_DRIVER}
      - MYSQL_PASSWORD=${DB_PASS}
      - DATABASE_HOST=${DB_HOST}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  book_server:
    container_name: book_server
    build: .
    image: book_server:latest
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3030:3030"
volumes:
  mysql_data:

